-- #######################################
-- ## Project: MTA Your-Life    	    ##
-- ## Name: DevEditor_Base.lua        	##
-- ## Author: StiviK        			##
-- ## Version: 1.0						##
-- #######################################