-- #######################################
-- ## Project: 	MTA Your-Life		    ##
-- ## Name: 	cTollStations.lua   	##
-- ## Author: 	StiviK					##
-- ## Version: 	1.0						##
-- #######################################